### ISSUE TITLE
Redirecting to / on login, not taking in account ABSOLUTE_URI

### ISSUE THREAD

**Issue by ahfeel** [nazar-pc/docker-phpmyadmin#15]
Hi,

I recently upgraded to the latest version of the image (I was previously using 4.6.1 I think), and since this upgrade I have an annoying issue when logging into phpmyadmin.

My phpmyadmin is proxied from an apache an lies on https://xxxx/phpmyadmin/, it used to work just fine, but since the upgrade it now redirect automatically after the login to https://xxx/. I have to manually go back to /phpmyadmin/.

Any idea on why this happens ?

Thanks !

**Comment by nazar-pc** [comment]
There was no changes relevant to this in Docker image recently: https://github.com/nazar-pc/docker-phpmyadmin/compare/4.5.4+build-1...master
This is either something in PhpMyAdmin itself, or in your particular setup.
Can you give me details of your Apache config, so that I can reproduce issue myself?

**Comment by nazar-pc** [comment]
I've also added:

```
Alias /phpmyadmin /var/www/html
```

To one of my instances and `/phpmyadmin` path works just fine, no redirects you've mentioned, so might be related to your proxy config as well.

**Comment by ahfeel** [comment]
Ok i found what was the issue, I added the `RequestHeader unset Proxy early` directive to my apache because of the vulnerability discovered a few weeks ago... Not an issue with your image then ;) Sorry :)
