### ISSUE TITLE
Provide Alpine version

### ISSUE THREAD

**Issue by davidwindell** [nazar-pc/docker-phpmyadmin#19]
To reduce disk footprint, it would be great to have an Alpine version which could extend from `php:7.1-alpine`.

A shared shell script could be used by two Dockerfiles to determine which is in use (something like this https://github.com/davidwindell/che/blob/master/agents/exec/src/main/resources/org.eclipse.che.exec.script.sh#L102).

**Comment by nazar-pc** [comment]
Honestly, I have no plans to add Alpine-based image here. It is smaller in general, but I'm typically using it with other official `debian:jessie`-based images (like these: https://github.com/nazar-pc/docker-webserver) overhead is basically negligible, since base image is the same and I assume software added on top of base image should be comparable in size.

Also I do not want to maintain something that I'm not familiar with (all of my systems are Debian/Ubuntu).

In my opinion maintenance burden doesn't really worth minor benefits in size.

What are your use cases where Alpine-based image might fit better?

**Comment by davidwindell** [comment]
I think we're talking about a 50mb saving in compressed download and around 175mb uncompressed. As this is such a simple tool that can be spun up at a moments notice, it would be more appealing I think if it was that little bit faster.

Happy to close this for now until there's more community support.
