### ISSUE TITLE
Consider GPL v3 or MIT license

### ISSUE THREAD

**Issue by bittner** [nazar-pc/docker-phpmyadmin#23]
According to the README this project source code is in the Public Domain.

You may want to consider putting it under [GPL v3](https://www.gnu.org/licenses/gpl-3.0.en.html) or, at least, the [MIT license](https://opensource.org/licenses/MIT).

The former would ensure that the code remains free/libre forever, the latter that you're not liable for potential damages caused by the code.

See also [GitHub's guide](https://choosealicense.com/licenses/) on licenses.

**Comment by nazar-pc** [comment]
I was using MIT for many of my other projects before and now switching to Free Public License 1.0.0 / Zero Clause BSD License, which are effectively public domain.

GPL v3 and MIT licenses have certain restrictions, however, I have no plans to prosecute anyone violating those restrictions, making them effectively useless. Also I have yet to see someone to be liable for something caused by public domain code.

So from my point of view something like 0BSD is a conscious choice, not a random decision caused by lack of interest or knowledge.

I appreciate your contributions and interest though.
