### ISSUE TITLE
Adding tags to the image on docker hub

### ISSUE THREAD

**Issue by aanc** [nazar-pc/docker-phpmyadmin#5]
Hello,

First, thanks for providing this image, it's really helpful !

I'm using this image in an automated deployment playbook (with Ansible). In that scope, it would be nice to be able to pull the exact same image at each execution of the playbook, in order to have a predictible and reproductible environment. The fact that 'latest' is the only tag available for this image prevent that.

Would it be possible to tag the images pushed on docker hub with the phpmyadmin version ?

Thanks in advance

**Comment by nazar-pc** [comment]
I thought about that from the very beginning.

New releases are out quite often, but since Docker Hub doesn't have possibility to import tags from Git repository I'd need to add each tag manually, which is boring and error-prone.

Also since PhpMyAdmin is self-contained utility, I decided to leave just `latest` tag which corresponds to latest stable upstream release (Docker image is usually out within few hours after PhpMyAdmin release, sometimes within an hour).
So, generally it is not recommended to rely on old versions with known bugs and security issues that were fixed already.

I'd add tags if they would be imported to Docker Hub from Git, otherwise it is too boring for me.

**Comment by nazar-pc** [comment]
@aanc, good news on this issue.
Docker Hub should start supporting dynamic tags next week, so this issue might be resolved.

**Comment by aanc** [comment]
Great ! Thanks :)

**Comment by nazar-pc** [comment]
First tagged build [already available](https://hub.docker.com/r/nazarpc/phpmyadmin/tags/), so I'm closing this.
